-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 13:04:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webphone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webphone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webphone` DEFAULT CHARACTER SET utf8 ;
USE `webphone` ;

-- -----------------------------------------------------
-- Table `webphone`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`accounts` ;

CREATE TABLE IF NOT EXISTS `webphone`.`accounts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `webphone`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`users` ;

CREATE TABLE IF NOT EXISTS `webphone`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT(10) UNSIGNED NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `login` VARCHAR(128) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `default_theme` TINYINT(1) UNSIGNED NULL,
  `default_language` CHAR(2) NULL,
  `default_timezone` TINYINT(1) UNSIGNED NULL,
  `default_ring_sound` VARCHAR(32) NULL,
  `email` VARCHAR(128) NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `acc_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `acc_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `webphone`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`lines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`lines` ;

CREATE TABLE IF NOT EXISTS `webphone`.`lines` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `host` VARCHAR(255) NOT NULL,
  `port` VARCHAR(10) NULL,
  `user` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `accl_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `accl_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `webphone`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`users_lines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`users_lines` ;

CREATE TABLE IF NOT EXISTS `webphone`.`users_lines` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `line_id` INT(10) UNSIGNED NOT NULL,
  `connect_limit` TINYINT(3) UNSIGNED NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `usli_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `usli_line_id_idx` (`line_id` ASC) VISIBLE,
  CONSTRAINT `usli_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `webphone`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usli_line_id`
    FOREIGN KEY (`line_id`)
    REFERENCES `webphone`.`lines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`users_preferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`users_preferences` ;

CREATE TABLE IF NOT EXISTS `webphone`.`users_preferences` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `ip_address` VARCHAR(32) NULL,
  `day_start` TINYINT(1) UNSIGNED NULL,
  `day_end` TINYINT(1) UNSIGNED NULL,
  `time_start` TIME NULL,
  `time_end` TIME NULL,
  `two_factor_auth` TINYINT(1) UNSIGNED NULL,
  `countries_auth` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  INDEX `uspr_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `uspr_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `webphone`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webphone`.`users_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`users_permissions` ;

CREATE TABLE IF NOT EXISTS `webphone`.`users_permissions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `us_pr_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `us_pr_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `webphone`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`groups` ;

CREATE TABLE IF NOT EXISTS `webphone`.`groups` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `class` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gr_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `gr_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `webphone`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`groups_elements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`groups_elements` ;

CREATE TABLE IF NOT EXISTS `webphone`.`groups_elements` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` INT(10) UNSIGNED NOT NULL,
  `element` TINYINT(1) UNSIGNED NOT NULL,
  `element_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gr_el_group_id_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `gr_el_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `webphone`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`tags` ;

CREATE TABLE IF NOT EXISTS `webphone`.`tags` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tg_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `tg_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `webphone`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`contacts` ;

CREATE TABLE IF NOT EXISTS `webphone`.`contacts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT(10) UNSIGNED NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `country` CHAR(2) NOT NULL,
  `source` TINYINT(1) UNSIGNED NOT NULL,
  `favorite` TINYINT(1) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `cn_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `cn_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `webphone`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`tags_contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`tags_contacts` ;

CREATE TABLE IF NOT EXISTS `webphone`.`tags_contacts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `tag_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `date_attach` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ta_cn_tag_id_idx` (`tag_id` ASC) VISIBLE,
  INDEX `ta_cn_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `ta_cn_contact_id_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `ta_cn_contact_id`
    FOREIGN KEY (`contact_id`)
    REFERENCES `webphone`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ta_cn_tag_id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `webphone`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ta_cn_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `webphone`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`contacts_numbers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`contacts_numbers` ;

CREATE TABLE IF NOT EXISTS `webphone`.`contacts_numbers` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `class` TINYINT(1) UNSIGNED NOT NULL,
  `number` VARCHAR(32) NOT NULL,
  `default` TINYINT(1) UNSIGNED NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cn_nu_contact_id_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `cn_nu_contact_id`
    FOREIGN KEY (`contact_id`)
    REFERENCES `webphone`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`contacts_notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`contacts_notes` ;

CREATE TABLE IF NOT EXISTS `webphone`.`contacts_notes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `note` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cn_nt_contact_id_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `cn_nt_contact_id`
    FOREIGN KEY (`contact_id`)
    REFERENCES `webphone`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`integrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`integrations` ;

CREATE TABLE IF NOT EXISTS `webphone`.`integrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT(10) UNSIGNED NOT NULL,
  `app_id` INT(10) UNSIGNED NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `in_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `in_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `webphone`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `webphone`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webphone`.`logs` ;

CREATE TABLE IF NOT EXISTS `webphone`.`logs` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `element` TINYINT(1) UNSIGNED NOT NULL,
  `element_id` INT(10) UNSIGNED NOT NULL,
  `action_date` DATE NOT NULL,
  `ip_address` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lo_account_id_idx` (`account_id` ASC) VISIBLE,
  INDEX `lo_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `lo_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `webphone`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lo_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `webphone`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
